### ISSUE TITLE
Citex not found

### ISSUE THREAD

**Issue by vseehausen** [hassox/phoenix_guardian#18]
```
19:03:43.347 [info]  == Running PhoenixGuardian.Repo.Migrations.CreateUser.change/0 forward

19:03:43.351 [info]  execute "CREATE EXTENSION citext;"
** (Postgrex.Error) ERROR (undefined_file): could not open extension control file  "/usr/share/postgresql/9.3/extension/citext.control"
```

Does this repo depend on citext? Which version of psql is required? 9.5? http://www.postgresql.org/docs/current/static/citext.html

Lets close this soon :+1:

**Comment by hassox** [comment]
I've used citext for a number of versions (All > 9) Are you using a pre 9 version of postgres?

**Comment by vseehausen** [comment]
Jap, I used 9.3. I installed 9.5 now, and I get the error message:
`** (Postgrex.Error) ERROR (undefined_object): type "jsonb" does not exist
`

**Comment by vseehausen** [comment]
Ok, git it working...

**Comment by Valentin-Seehausen** [comment]
Just before close:

Do I have to do something spe
