### ISSUE TITLE
Read permissions from config file on run instead of compilation

### ISSUE THREAD

**Issue by wende** [hassox/phoenix_guardian#20]
`Guardian.Permissions` module reads the permissions from the config file during compilation time instead of runtime.
Because of that changing the `config.exs` file has no effect post deps compilation, and do change config you need to clear the `_deps` folder, which shouldn't be the desired behaviour

**Comment by hassox** [comment]
Hey @wende 

Guardian used to do this. It's been updated to read the permissions at runtime now rather than compile time. Would gladly take a PR that updates to the latest version of guardian.

**Comment by hassox** [comment]
I've updated guardian on the main (ueberauth-guardian) branch
