### ISSUE TITLE
Update example to latest Guardian, Phoenix and Guardian_db versions

### ISSUE THREAD

**Issue by Pjino** [hassox/phoenix_guardian#3]
Just to make sure everything is OK without the need of tweaking things.

**Comment by Donwangugi** [comment]
Bump :)

**Comment by Pjino** [comment]
@Donwangugi Thanks!

**Comment by doomspork** [comment]
The best outcome for this is if someone puts in the work and opens a PR.  That said I pulled the project, bumped the dependency versions, and a whole slew of things broke.  I'm going to try updating the project for Phoenix 1.0 and Guardian 6.2 but it's further down on my list of things to do.

**Comment by doomspork** [comment]
@Pjino and @Donwangugi see PR #5 for updated dependencies and tests.  Thoughts/feedback always appreciated :grinning:

**Comment by Pjino** [comment]
@doomspork . Thanks a lot. I must confess that I'm not (yet) of great help because I'm in my first steps in  software development/Github and I don't know how to access your changes (I still see the latest commit in 23rd August...)

**Comment by doomspork** [comment]
Good morning @Pjino, that is no problem!  

I opened a Pull Request for my changes so you can start there.  If you click [here](https://github.com/hassox/phoenix_guardian/pull/5) and then "Files Changed" you'll see the modifications I needed to make.  To see my changes in their entirety you can peek at my fork, specifically the branch "update_dependencies", found [here](https://github.com/doomspork/phoenix_guardian/tree/update-dependencies).

Hope that helps :grinning:

**Comment by hassox** [comment]
I've updated the app and changed it's default branch. It was a full re-generate.
