### ISSUE TITLE
Duplicate user in the database when signing-up

### ISSUE THREAD

**Issue by Pjino** [hassox/phoenix_guardian#4]
I used your example code in my project and everything is working except that when I create a new user it creates two equal users in the database. Do you have an idea where the bug is (or is it me that changed something because you example is working properly with you?).

**Comment by ddcech** [comment]
I have the same thing happening.

**Comment by ddcech** [comment]
I removed any trace of `plug :action` in my controllers. Removing it from my `user_controller.ex` fixed the issue. 

Found it here. SHA: c5bf0edf1fd64ecbf7d16ac0a45fb4f2fd10be6b

**Comment by Pjino** [comment]
@DeodorantMan That's it! This should be solved for everybody when the example is updated to comply with the latest Phoenix version. Thank you.
