### ISSUE TITLE
Unable to complile

### ISSUE THREAD

**Issue by stevenlivz** [hassox/phoenix_guardian#6]
Installed latest Phoenix etc per the docs on Mac El Capitan. Cloned this repo. Followed instructions and I get :

```
== Compilation error on file lib/comeonin/bcrypt.ex ==
** (MatchError) no match of right hand side value: {:error, :on_load_failure}
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6


16:31:11.166 [error] Process #PID<0.301.0> raised an exception
** (MatchError) no match of right hand side value: {:error, {:load_failed, 'Failed to load NIF library: \'dlopen(/Users/livz/dev/code/play/old/phoenix_guardian/_build/dev/lib/comeonin/priv/bcrypt_nif.so, 2): image not found\''}}
    lib/comeonin/bcrypt.ex:28: Comeonin.Bcrypt.init/0
    (kernel) code_server.erl:1674: anonymous fn/1 in :code_server.handle_on_load/4
could not compile dependency :comeonin, "mix compile" failed. You can recompile this dependency with "mix deps.compile comeonin", update it with "mix deps.update comeonin" or clean it with "mix deps.clean comeonin"

16:31:11.168 [warn]  The on_load function for module Elixir.Comeonin.Bcrypt returned {{:badmatch,
  {:error,
   {:load_failed,
    'Failed to load NIF library: \'dlopen(/Users/livz/dev/code/play/old/phoenix_guardian/_build/dev/lib/comeonin/priv/bcrypt_nif.so, 2): image not found\''}}},
 [{Comeonin.Bcrypt, :init, 0, [file: 'lib/comeonin/bcrypt.ex', line: 28]},
  {:code_server, :"-handle_on_load/4-fun-0-", 1,
   [file: 'code_server.erl', line: 1674]}]}
```

The tried mix deps.compile comeonin and mix phoenix.server:

```
== Compilation error on file lib/phoenix/code_reloader.ex ==
** (CompileError) lib/phoenix/code_reloader.ex:61: function full_path/1 undefined
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
```

Following any further instructions give the same exception.

I tried getting the unmerged pull but had issues with that as well. Any ideas?

**Comment by hassox** [comment]
Unfortunately I'm not able to upgrade to El Capitan atm due to work. This looks like Comeonin is unable to compile. Are you able to include that as a dependency and compile without Guardian?

**Comment by stevenlivz** [comment]
Thanks. I am able to create a Phoenix app that uses Comeonin and talks to Postgres. This was the next step up from using passwords. Maybe something to do with versions.

**Comment by hassox** [comment]
Oh sorry I'm looking at the wrong repo :\

This repo as it currently stands is terribly out of date :( I'm working on getting it up to speed at the moment. It shouldn't be too much longer before it's good to go.

**Comment by stevenlivz** [comment]
That would be great. I managed to get jwt/jose working with phoenix so i suspect it's just versioning which i may try to look into later. thanks.
